"""Render findings into review reports (markdown)."""

from __future__ import annotations

from collections import Counter

from .checks import Finding

_SEV_ORDER = {"critical": 0, "major": 1, "minor": 2, "unknown": 3}
_SEV_ICON = {"critical": "🔴", "major": "🟠", "minor": "🟡", "unknown": "⚪"}


def render_markdown(findings: list[Finding], title: str = "Manuscript review",
                    source: str | None = None) -> str:
    lines = [f"# {title}", ""]
    if source:
        lines += [f"*Manuscript: `{source}`*", ""]

    if not findings:
        lines += ["No findings. (Deterministic checks only — the semantic "
                  "rules still need an LLM/human pass.)", ""]
        return "\n".join(lines)

    sev = Counter(f.severity for f in findings)
    summary = " · ".join(
        f"{_SEV_ICON[s]} {sev[s]} {s}" for s in ("critical", "major", "minor")
        if sev.get(s)
    )
    lines += [f"**{len(findings)} findings** — {summary}", ""]

    by_rule: dict[str, list[Finding]] = {}
    for f in findings:
        by_rule.setdefault(f.rule_id, []).append(f)

    for rule_id in sorted(by_rule,
                          key=lambda r: (_SEV_ORDER.get(by_rule[r][0].severity, 3), r)):
        fs = by_rule[rule_id]
        lines += [f"## {_SEV_ICON.get(fs[0].severity, '⚪')} {rule_id} "
                  f"({fs[0].severity}) — {len(fs)} finding(s)", ""]
        for f in fs:
            loc = f"line {f.line}" if f.line else "global"
            flag = " *(candidate — verify)*" if f.confidence == "candidate" else ""
            lines.append(f"- **[{loc}]** {f.message}{flag}")
            if f.excerpt:
                lines.append(f"  > {f.excerpt}")
            if f.suggestion:
                lines.append(f"  - 💡 {f.suggestion}")
        lines.append("")

    lines += ["---",
              "*Generated by the [Scientific Writing Agent]"
              "(https://github.com/alhermann/scientific-writing-agent) — "
              "deterministic findings are reliable; items marked `candidate` "
              "need semantic confirmation.*", ""]
    return "\n".join(lines)
